version: '3'

services:
  server:
    container_name: c_server1
    build:
      context: ./app
    restart: unless-stopped  
    ports:
      - 3000:3000 
    volumes:
      - ./app:/usr/src/app
      - server:/usr/src/app/node_modules 
    networks:
      - backend   

  nginx:
    container_name: c_nginx    
    build:
        context: ./nginx
    restart: unless-stopped
    ports:
        - 8080:80
    depends_on:
      - server
    networks:
      - backend   

volumes:
  server:

networks:
  backend:


