version: '3'

services:
  server:
    container_name: c_server
    build:
      context: ../node-app
      dockerfile: Dockerfile
    restart: unless-stopped  
    ports:
      - "3000:3000"
    volumes:
      - ../node-app:/usr/src/app
      - server:/usr/src/app/node_modules 
    networks:
      - backend   

  nginx:
    container_name: c_nginx    
    build:
        context: ./
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - backend   

volumes:
  server:

networks:
  backend:


